apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: staging-production
  annotations:
    description: ""
spec:
  triggerEnvironment: dev
  steps:
    - environment: Prod
      dependsOn:
        - dev
      policy:
        action: commit